In [214]:
import numpy as np 
import pandas as pd

In [215]:
v = pd.read_csv("movies-tmdb-10000.csv")

In [216]:
v.head(2)

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731

In [217]:


# we can see here my  how many columns are present 
# in my original movie dataset

In [218]:

v.columns.tolist()

# we can see here my  how many columns are present 
# in my original movie dataset

['id',
 'title',
 'genre',
 'original_language',
 'overview',
 'popularity',
 'release_date',
 'vote_average',
 'vote_count']

In [219]:
v.shape
#   1000 rows and 16 columns are there

(10000, 9)

In [220]:
v.isnull().sum()
# only in 2 columns ,  our data is missing 
# since  we will impute rather than droping 
# the column because

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [221]:
# we are filling the missing value of overview 
# genre
v["overview"].fillna("Not Available",inplace=True)
v["genre"].fillna("- - -",inplace=True)

C:\Users\rahul\AppData\Local\Temp\ipykernel_35412\451296821.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  v["overview"].fillna("Not Available",inplace=True)
C:\Users\rahul\AppData\Local\Temp\ipykernel_35412\451296821.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  v["genre"].fillna("- - -",inplace=True)

In [222]:
v.isnull().sum()
# now no any  values is missing

id                   0
title                0
genre                0
original_language    0
overview             0
popularity           0
release_date         0
vote_average         0
vote_count           0
dtype: int64

In [223]:
# this is the code of text vectorization
#

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words="english")

In [224]:

v  =  movies_overview 

# we can see here my  how many columns are present 
# in my original movie dataset

In [225]:
v["overview"][1]

'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fianc√©. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.'

In [226]:
movies_overview = v

# we can see here my  how many columns are present 
# in my original movie dataset

In [227]:
movies =v[['id', 'title', 'overview', 'genre']]

In [228]:
movies.head(2)

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"

In [229]:
movies['tags'] = movies['overview'] + movies['genre']

C:\Users\rahul\AppData\Local\Temp\ipykernel_35412\2958959546.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] + movies['genre']

In [230]:
new_movies  = movies.drop(columns=['overview', 'genre'])
new_movies.head()

# what we did here is to  first we add drop and genre in single column 
#  tag then we dropped both column  and made new dataset

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...

In [231]:
new_movies["tags"][1]

'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fianc√©. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.Comedy,Drama,Romance'

In [232]:
from sklearn.feature_extraction.text import CountVectorizer

# so this line converts our text data into 
# numerical data ... actually what does it mean 
# that suppose  we have text 1 and text 2 ...
# so it will make a matrix of text 1 and text 2 
# and make a column of  words ... like words  
# i love thriller 
#  i love  roamnce 
# so by numerica coding it will tell the percentage of matching
# and used for recommending purpose from the basis ofd 1 movie

In [233]:
cv=CountVectorizer(max_features=10000, stop_words='english')
# since we have  10000 rows  and in tags there is so many words
#  so it will remove common words like and , the , is 
# because for tag puprpose it is irrelevent features

In [234]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [235]:
vectors =cv.fit_transform(new_movies['tags'].values.astype('U')).toarray()

In [236]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [237]:
from sklearn.metrics.pairwise import cosine_similarity

In [238]:
similarity=cosine_similarity(vector)
similarity

array([[1.        , 0.05555556, 0.12858612, ..., 0.0745356 , 0.10910895,
        0.06804138],
       [0.05555556, 1.        , 0.07715167, ..., 0.        , 0.03636965,
        0.        ],
       [0.12858612, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
        0.09449112],
       ...,
       [0.0745356 , 0.        , 0.02300219, ..., 1.        , 0.03253   ,
        0.03042903],
       [0.10910895, 0.03636965, 0.0673435 , ..., 0.03253   , 1.        ,
        0.04454354],
       [0.06804138, 0.        , 0.09449112, ..., 0.03042903, 0.04454354,
        1.        ]])

In [239]:
new_movies[new_movies['title']=="The Godfather"].index[0]

2

In [240]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_movies.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City

In [241]:
def recommand(movies):
    index=new_movies[new_movies['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_movies.iloc[i[0]].title)

In [242]:
recommand("Iron Man")

Iron Man
Iron Man 3
Guardians of the Galaxy Vol. 2
Avengers: Age of Ultron
Star Wars: Episode III - Revenge of the Sith

In [243]:
import pickle
pickle.dump(new_movies, open('movies_list.pkl', 'wb'))

In [244]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [245]:
pickle.load(open('movies_list.pkl', 'rb'))

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner‚Äôs murder by an...

In [246]:
pickle.dump(movies_overview, open('movies_overview.pkl', 'wb'))

In [247]:
pickle.load(open('movies_overview.pkl', 'rb'))

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner‚Äôs murder by an...,16.482,2019-05-31,4.6,221